### ISSUE TITLE
Incorrect steps for Titan Hybrid Extruders in README.md

### ISSUE THREAD

**Issue by TimVa** [BigBox3D/Firmware#1]
0.9° Stepper Motors Non-Titan Hybrid Extruders using the larger 0.9° Stepper Motors set the Steps-Per-MM to 304. Titan Hybrid Extruders using the larger 0.9° Stepper Motors set the Steps-Per-MM to **852**.

Should be 0.9° Stepper Motors Non-Titan Hybrid Extruders using the larger 0.9° Stepper Motors set the Steps-Per-MM to 304. Titan Hybrid Extruders using the larger 0.9° Stepper Motors set the Steps-Per-MM to **835**.

**Comment by BigBox3D** [comment]
Fixed, thanks :)
